services:
  server:
    build: ./Server
    ports:
      - "3030:3030"
    depends_on: 
      - mongo  
  
  client:
    build: ./Client
    ports:
      - "3000:3000"
    depends_on:
      - server
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"